import type {
  User,
  CarbonProject,
  CarbonCredit,
  Transaction,
  AdminStats,
  ComplianceAlert,
  BuyerPortfolio,
} from "./types";

// ─── Users ───────────────────────────────────────────────────────────────────
export const MOCK_USERS: User[] = [
  {
    id: "u001",
    name: "Priya Sharma",
    email: "admin@bcx.gov.in",
    role: "admin",
    organization: "Ministry of Environment, Forest & Climate Change",
    createdAt: "2024-01-15",
  },
  {
    id: "u002",
    name: "Arjun Mehta",
    email: "dev@greenenergy.in",
    role: "developer",
    organization: "Green Horizon Energy Pvt. Ltd.",
    createdAt: "2024-02-20",
  },
  {
    id: "u003",
    name: "Sunita Patel",
    email: "buyer@tatasteel.com",
    role: "buyer",
    organization: "Tata Steel Ltd.",
    createdAt: "2024-03-10",
  },
];

export const DEMO_CREDENTIALS = [
  { email: "admin@bcx.gov.in", password: "Admin@123", role: "admin" as const },
  { email: "dev@greenenergy.in", password: "Dev@123", role: "developer" as const },
  { email: "buyer@tatasteel.com", password: "Buyer@123", role: "buyer" as const },
];

// ─── Projects ────────────────────────────────────────────────────────────────
export const MOCK_PROJECTS: CarbonProject[] = [
  {
    id: "prj001",
    name: "Rajasthan Wind Power Initiative",
    developerId: "u002",
    developerName: "Green Horizon Energy Pvt. Ltd.",
    sector: "Renewable Energy",
    location: "Jaisalmer, Rajasthan",
    state: "Rajasthan",
    vintage: 2024,
    totalCredits: 50000,
    availableCredits: 32000,
    pricePerCredit: 850,
    status: "active",
    integrityScore: 92,
    methodology: "ACM0002 - Grid-connected electricity generation from renewable sources",
    description:
      "A 120 MW wind farm displacing coal-based grid electricity in the energy-deficit Rajasthan region, generating verified emission reductions for the Indian grid.",
    co2Reduction: 180000,
    sdgGoals: [7, 13, 8],
    createdAt: "2024-01-10",
    approvedAt: "2024-02-05",
  },
  {
    id: "prj002",
    name: "Western Ghats Afforestation",
    developerId: "u002",
    developerName: "Green Horizon Energy Pvt. Ltd.",
    sector: "Afforestation",
    location: "Sahyadri Range, Maharashtra",
    state: "Maharashtra",
    vintage: 2023,
    totalCredits: 25000,
    availableCredits: 18500,
    pricePerCredit: 620,
    status: "active",
    integrityScore: 88,
    methodology: "AR-AM0014 - Afforestation and reforestation of degraded lands",
    description:
      "Restoration of 5,000 hectares of degraded land in the Western Ghats biodiversity hotspot, sequestering carbon while restoring critical wildlife corridors.",
    co2Reduction: 75000,
    sdgGoals: [13, 15, 1],
    createdAt: "2023-08-20",
    approvedAt: "2023-10-15",
  },
  {
    id: "prj003",
    name: "Punjab Agricultural Methane Capture",
    developerId: "u004",
    developerName: "AgroCarbon Solutions",
    sector: "Methane Capture",
    location: "Ludhiana, Punjab",
    state: "Punjab",
    vintage: 2024,
    totalCredits: 15000,
    availableCredits: 15000,
    pricePerCredit: 940,
    status: "pending",
    integrityScore: 74,
    methodology: "AMS-III.D - Methane recovery in agricultural activities",
    description:
      "Biogas capture from rice paddy fields and dairy farms in Punjab, converting methane emissions into clean energy for rural communities.",
    co2Reduction: 42000,
    sdgGoals: [7, 2, 13],
    createdAt: "2024-04-01",
  },
  {
    id: "prj004",
    name: "Sundarbans Blue Carbon",
    developerId: "u005",
    developerName: "Blue Earth Foundation",
    sector: "Blue Carbon",
    location: "Sundarbans, West Bengal",
    state: "West Bengal",
    vintage: 2024,
    totalCredits: 8000,
    availableCredits: 8000,
    pricePerCredit: 1200,
    status: "pending",
    integrityScore: 95,
    methodology: "VM0033 - Methodology for tidal wetland and seagrass restoration",
    description:
      "Conservation and restoration of mangrove ecosystems in the Sundarbans delta, one of the world's largest carbon sinks, protecting biodiversity and coastal communities.",
    co2Reduction: 32000,
    sdgGoals: [14, 13, 15, 1],
    createdAt: "2024-05-15",
  },
  {
    id: "prj005",
    name: "Gujarat Solar Irrigation",
    developerId: "u002",
    developerName: "Green Horizon Energy Pvt. Ltd.",
    sector: "Energy Efficiency",
    location: "Kutch, Gujarat",
    state: "Gujarat",
    vintage: 2023,
    totalCredits: 12000,
    availableCredits: 9200,
    pricePerCredit: 710,
    status: "active",
    integrityScore: 85,
    methodology: "AMS-I.C - Thermal energy production with or without electricity",
    description:
      "Replacing diesel-powered water pumps with solar irrigation systems across 3,000 farms in Kutch, reducing emissions and energy costs for smallholder farmers.",
    co2Reduction: 28500,
    sdgGoals: [7, 2, 8],
    createdAt: "2023-11-01",
    approvedAt: "2024-01-10",
  },
  {
    id: "prj006",
    name: "Jharkhand Waste-to-Energy",
    developerId: "u006",
    developerName: "EcoVentures Jharkhand",
    sector: "Waste Management",
    location: "Ranchi, Jharkhand",
    state: "Jharkhand",
    vintage: 2024,
    totalCredits: 6000,
    availableCredits: 6000,
    pricePerCredit: 780,
    status: "rejected",
    integrityScore: 58,
    methodology: "ACM0022 - Alternative waste treatment processes",
    description:
      "Municipal solid waste processing facility converting organic waste to biogas and compost, diverting waste from open landfills.",
    co2Reduction: 18000,
    sdgGoals: [11, 13],
    createdAt: "2024-03-20",
  },
];

// ─── Transactions ─────────────────────────────────────────────────────────────
export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "txn001",
    type: "issuance",
    projectId: "prj001",
    projectName: "Rajasthan Wind Power Initiative",
    from: "BCX Registry",
    to: "Green Horizon Energy Pvt. Ltd.",
    quantity: 50000,
    timestamp: "2024-02-05T09:30:00Z",
    blockHash: "0x4f3a...b82c",
    status: "confirmed",
  },
  {
    id: "txn002",
    type: "purchase",
    projectId: "prj001",
    projectName: "Rajasthan Wind Power Initiative",
    from: "Green Horizon Energy Pvt. Ltd.",
    to: "Tata Steel Ltd.",
    quantity: 10000,
    pricePerCredit: 850,
    totalValue: 8500000,
    timestamp: "2024-03-15T14:22:00Z",
    blockHash: "0x8d1e...f4a7",
    status: "confirmed",
  },
  {
    id: "txn003",
    type: "retirement",
    projectId: "prj001",
    projectName: "Rajasthan Wind Power Initiative",
    from: "Tata Steel Ltd.",
    to: "BCX Registry (Retired)",
    quantity: 5000,
    timestamp: "2024-04-02T11:00:00Z",
    blockHash: "0x2c9b...e31f",
    status: "confirmed",
  },
  {
    id: "txn004",
    type: "purchase",
    projectId: "prj002",
    projectName: "Western Ghats Afforestation",
    from: "Green Horizon Energy Pvt. Ltd.",
    to: "Reliance Industries Ltd.",
    quantity: 6500,
    pricePerCredit: 620,
    totalValue: 4030000,
    timestamp: "2024-04-18T16:45:00Z",
    blockHash: "0x7a4d...c19e",
    status: "confirmed",
  },
  {
    id: "txn005",
    type: "issuance",
    projectId: "prj002",
    projectName: "Western Ghats Afforestation",
    from: "BCX Registry",
    to: "Green Horizon Energy Pvt. Ltd.",
    quantity: 25000,
    timestamp: "2023-10-15T08:00:00Z",
    blockHash: "0x3b8c...d72a",
    status: "confirmed",
  },
  {
    id: "txn006",
    type: "purchase",
    projectId: "prj005",
    projectName: "Gujarat Solar Irrigation",
    from: "Green Horizon Energy Pvt. Ltd.",
    to: "Tata Steel Ltd.",
    quantity: 2800,
    pricePerCredit: 710,
    totalValue: 1988000,
    timestamp: "2024-05-01T10:30:00Z",
    blockHash: "0x9f2a...b45e",
    status: "confirmed",
  },
  {
    id: "txn007",
    type: "transfer",
    projectId: "prj002",
    projectName: "Western Ghats Afforestation",
    from: "Reliance Industries Ltd.",
    to: "HDFC Bank Ltd.",
    quantity: 1000,
    pricePerCredit: 650,
    totalValue: 650000,
    timestamp: "2024-05-10T13:15:00Z",
    blockHash: "0x1d6f...a93c",
    status: "pending",
  },
];

// ─── Admin Stats ──────────────────────────────────────────────────────────────
export const MOCK_ADMIN_STATS: AdminStats = {
  totalCreditsIssued: 116000,
  totalCreditsTraded: 38300,
  totalCreditsRetired: 5000,
  pendingApprovals: 2,
  activeProjects: 3,
  registeredDevelopers: 12,
  registeredBuyers: 47,
  monthlyVolume: [
    { month: "Dec 23", volume: 8200, value: 6150000 },
    { month: "Jan 24", volume: 12400, value: 9300000 },
    { month: "Feb 24", volume: 9800, value: 7350000 },
    { month: "Mar 24", volume: 15600, value: 11700000 },
    { month: "Apr 24", volume: 11200, value: 8400000 },
    { month: "May 24", volume: 18300, value: 13725000 },
  ],
};

// ─── Compliance Alerts ────────────────────────────────────────────────────────
export const MOCK_COMPLIANCE_ALERTS: ComplianceAlert[] = [
  {
    id: "ca001",
    type: "critical",
    entity: "EcoVentures Jharkhand",
    message:
      "Project prj006 failed integrity verification. AI score below threshold (58/100). Immediate review required.",
    projectId: "prj006",
    timestamp: "2024-05-15T08:00:00Z",
    resolved: false,
  },
  {
    id: "ca002",
    type: "warning",
    entity: "AgroCarbon Solutions",
    message:
      "MRV documentation for prj003 is 14 days overdue. Project cannot be approved until documents are submitted.",
    projectId: "prj003",
    timestamp: "2024-05-10T12:00:00Z",
    resolved: false,
  },
  {
    id: "ca003",
    type: "info",
    entity: "BCX System",
    message:
      "Quarterly audit cycle initiated. 3 projects selected for random verification sampling.",
    timestamp: "2024-05-01T09:00:00Z",
    resolved: false,
  },
  {
    id: "ca004",
    type: "warning",
    entity: "Green Horizon Energy Pvt. Ltd.",
    message:
      "Carbon credit serial BCX-PRJ001-2024-8821 to 8890 flagged for double-counting risk. Verification in progress.",
    projectId: "prj001",
    timestamp: "2024-04-28T15:30:00Z",
    resolved: true,
  },
];

// ─── Buyer Portfolio ──────────────────────────────────────────────────────────
export const MOCK_BUYER_PORTFOLIO: BuyerPortfolio = {
  totalCreditsOwned: 7800,
  totalCreditsRetired: 5000,
  totalSpent: 10488000,
  carbonOffset: 5000,
  holdings: [
    {
      projectId: "prj001",
      projectName: "Rajasthan Wind Power Initiative",
      sector: "Renewable Energy",
      quantity: 5000,
      avgPrice: 850,
      currentPrice: 880,
      purchasedAt: "2024-03-15",
    },
    {
      projectId: "prj005",
      projectName: "Gujarat Solar Irrigation",
      sector: "Energy Efficiency",
      quantity: 2800,
      avgPrice: 710,
      currentPrice: 710,
      purchasedAt: "2024-05-01",
    },
  ],
};
